name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn --frozen-lockfile && yarn format
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn --frozen-lockfile && yarn lint
